spring.application.name=SmartInventoryManagementSystem
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Connection Pool Settings (optional)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Always run schema/data scripts if you have them
spring.sql.init.mode=always

# Optional: Log SQL statements
logging.level.org.springframework.jdbc.core=DEBUG

# application.properties
jwt.secret=THIS_SHOULD_BE_LONG_RANDOM_STRING
jwt.expirationMs=86400000