spring.application.name=SmartInventoryManagementSystem
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Always run schema/data scripts if you have them
spring.sql.init.mode=always

# Optional: Log SQL statements
logging.level.org.springframework.jdbc.core=DEBUG
